server:
  port: 8060
  error:
    include-message: always

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


management:
  tracing:
    sampling:
      probability: 1.0


spring:
  application:
    name: api-gateway

  config:
    import: "optional:configserver:http://localhost:8088"

  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
      routes:
        - id: employee-service
          uri: lb://employee-service
          predicates:
            - Path=/api/employee/**
          filters:
            - AuthenticationFilter

        - id: department-service
          uri: lb://department-service
          predicates:
            - Path=/api/department/**
          filters:
            - AuthenticationFilter

        - id: position-service
          uri: lb://position-service
          predicates:
            - Path=/api/position/**
          filters:
            - AuthenticationFilter

        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**